blank_issues_enabled: false

contact_links:

  - name: Consider contributing / donating
    url: https://www.buymeacoffee.com/ivan.pinatti
    about: |-
      I code this on my free time, please consider donating to support the project
